---
title: "iDAPT-MS and SARS-CoV-2 R Markdown"
output: html_document
date: '2023-10-23'
---

```{r, eval=T}
library(stringr)
library(DESeq2)
library(ggplot2)
library(ggrepel)
library(pheatmap)
```

# Vero VOC spike ATAC-seq analysis

```{r, eval=T}
# read in ATAC-seq read pileups within peaks from bash
atac_counts <- read.table(file="DATASETS/atacseq_vero_voc_spike_counts.txt", header=T)

# read in ATAC-seq library information
sampleinfo <- data.frame(row.names=colnames(atac_counts),
                         Group=unlist(strsplit(colnames(atac_counts), "[.]"))[c(F,F,T,F,F)])
sampleinfo$Group <- factor(sampleinfo$Group, levels=c("EGFP", "Spike", "Alpha", "Delta"))
```

```{r, eval=T}
atac_dds <- DESeqDataSetFromMatrix(countData = atac_counts, colData = sampleinfo, design = ~Group)
atac_dds$Group <- relevel(atac_dds$Group, "EGFP")
atac_dds <- estimateSizeFactors(atac_dds)
```

```{r, eval=T}
atac_dds <- DESeq(atac_dds)
```

```{r, eval=T}
vero_spike_results <- data.frame(lfcShrink(dds=atac_dds, coef=2)) 
vero_alpha_results <- data.frame(lfcShrink(dds=atac_dds, coef=3))
vero_delta_results <- data.frame(lfcShrink(dds=atac_dds, coef=4))
```

```{r, eval=T, fig.width=1.5, fig.height=1.5}
ggplot(vero_spike_results, aes(x=log2FoldChange, y=-log10(padj))) + geom_point(pch=20, color="lightgray", alpha=0.5, data=subset(subset(vero_spike_results), padj > 0.05)) + geom_point(pch=20, color="skyblue", data=subset(subset(vero_spike_results), padj < 0.05 & log2FoldChange < 0), alpha=0.5) + geom_point(pch=20, color="indianred", data=subset(subset(vero_spike_results), padj < 0.05 & log2FoldChange > 0), alpha=0.5) + theme_classic() + geom_hline(yintercept=0, lty=3) + xlim(c(-3.5,3.5)) + ylim(c(0,45)) + 
  geom_hline(yintercept=-log10(0.05), lty=3, color="red") + geom_vline(xintercept=0, lty=3, color="red") + ylab("-Log10 FDR") + xlab("ATAC-seq Log2 Fold Change,\nVero Spike vs. EGFP")

ggplot(vero_alpha_results, aes(x=log2FoldChange, y=-log10(padj))) + geom_point(pch=20, color="lightgray", alpha=0.5, data=subset(subset(vero_alpha_results), padj > 0.05)) + geom_point(pch=20, color="skyblue", data=subset(subset(vero_alpha_results), padj < 0.05 & log2FoldChange < 0), alpha=0.5) + geom_point(pch=20, color="indianred", data=subset(subset(vero_alpha_results), padj < 0.05 & log2FoldChange > 0), alpha=0.5) + theme_classic() + geom_hline(yintercept=0, lty=3) + xlim(c(-3.5,3.5)) + ylim(c(0,45)) + 
  geom_hline(yintercept=-log10(0.05), lty=3, color="red") + geom_vline(xintercept=0, lty=3, color="red") + ylab("-Log10 FDR") + xlab("ATAC-seq Log2 Fold Change,\nVero Alpha vs. EGFP")

ggplot(vero_delta_results, aes(x=log2FoldChange, y=-log10(padj))) + geom_point(pch=20, color="lightgray", alpha=0.5, data=subset(subset(vero_delta_results), padj > 0.05)) + geom_point(pch=20, color="skyblue", data=subset(subset(vero_delta_results), padj < 0.05 & log2FoldChange < 0), alpha=0.5) + geom_point(pch=20, color="indianred", data=subset(subset(vero_delta_results), padj < 0.05 & log2FoldChange > 0), alpha=0.5) + theme_classic() + geom_hline(yintercept=0, lty=3) + xlim(c(-3.5,3.5)) + ylim(c(0,45)) + 
  geom_hline(yintercept=-log10(0.05), lty=3, color="red") + geom_vline(xintercept=0, lty=3, color="red") + ylab("-Log10 FDR") + xlab("ATAC-seq Log2 Fold Change,\nVero Delta vs. EGFP")
```

```{r, eval=T}
# read in ATAC-seq read pileups within peaks from bash
atac_nut_counts <- read.table(file="DATASETS/atacseq_vero_nutlin_counts.txt", header=T)
sampleinfo_nut <- data.frame(row.names=colnames(atac_nut_counts),
                         Group = unlist(strsplit(colnames(atac_nut_counts), "[.]"))[c(F,T,F)])
```

```{r, eval=T}
atac_nut_dds <- DESeqDataSetFromMatrix(countData = atac_nut_counts, colData = sampleinfo_nut, design = ~Group)
atac_nut_dds <- estimateSizeFactors(atac_nut_dds)
atac_nut_dds <- DESeq(atac_nut_dds)
```

```{r, eval=F}
atac_results_vero_nut <- data.frame(lfcShrink(atac_nut_dds, coef=2))
```

```{r, eval=T, fig.width=1.5, fig.height=1.5}
ggplot(atac_results_vero_nut, aes(x=log2FoldChange, y=-log10(padj))) + geom_point(pch=20, color="lightgray", alpha=0.5, data=subset(atac_results_vero_nut, padj > 0.05)) + geom_point(pch=20, color="indianred", data=subset(atac_results_vero_nut, padj < 0.05 & log2FoldChange > 0), alpha=0.5) + geom_point(pch=20, color="skyblue", data=subset(atac_results_vero_nut, padj < 0.05 & log2FoldChange < 0), alpha=0.5) + theme_classic() + geom_hline(yintercept=0, lty=3) +
  geom_hline(yintercept=-log10(0.05), lty=3, color="red") + geom_vline(xintercept=0, lty=3, color="red") + ylab("-Log10 FDR") + xlab("ATAC-seq Log2 Fold Change\nVero Nutlin-3a vs. DMSO") #+ xlim(c(-10,10)) + ylim(c(0,300))
```

```{r, eval=T}
cor_delta <- cor.test((subset(merge(atac_results_vero_nut, vero_delta_results, by=0), padj.x < 0.05 & padj.y < 0.05)$log2FoldChange.x),
    (subset(merge(atac_results_vero_nut, vero_delta_results, by=0), padj.x < 0.05 & padj.y < 0.05)$log2FoldChange.y))

cor_alpha <- cor.test((subset(merge(atac_results_vero_nut, vero_alpha_results, by=0), padj.x < 0.05 & padj.y < 0.05)$log2FoldChange.x),
    (subset(merge(atac_results_vero_nut, vero_alpha_results, by=0), padj.x < 0.05 & padj.y < 0.05)$log2FoldChange.y))

cor_spike <- cor.test((subset(merge(atac_results_vero_nut, vero_spike_results, by=0), padj.x < 0.05 & padj.y < 0.05)$log2FoldChange.x),
    (subset(merge(atac_results_vero_nut, vero_spike_results, by=0), padj.x < 0.05 & padj.y < 0.05)$log2FoldChange.y))
```

```{r, eval=T}
cor_df <- data.frame(voc = factor(c("Spike", "Alpha", "Delta"), levels=rev(c("Spike", "Alpha", "Delta"))),
                     cor = c(cor_spike$estimate, cor_alpha$estimate, cor_delta$estimate), 
                     pval = c(cor_spike$p.value, cor_alpha$p.value, cor_delta$p.value))
cor_df
```

```{r, eval=T, fig.width=2, fig.height=1.2}
ggplot(cor_df, aes(y = cor, x = voc)) +
  geom_segment(yend=0, aes(xend=voc), lty=3) + theme_classic() + ylab("Pearson Correlation\nvs. Nutlin-3a Treatment\nATAC-seq") + 
  geom_point(aes(color=(pval)))  +
  xlab("") + coord_flip() + 
  theme(legend.position = "right", axis.text.y = element_text(vjust=0.5)) +
  scale_color_continuous(low="red", high="blue", name="p-value") +
  geom_hline(yintercept=0, lwd=0.1) + ylim(c(0,1))
```

```{r, eval=T, fig.width=1.5, fig.height=1.5}
ggplot(subset(merge(atac_results_vero_nut, vero_delta_results, by=0), padj.x < 00.05 & padj.y < 00.05)) + geom_point(aes(x=(log2FoldChange.x), y=(log2FoldChange.y)), alpha=0.2, pch=1) + xlim(c(-3.5,3.5)) + ylim(c(-3.5,3.5)) + geom_smooth(method="lm", formula=y~x, aes(x=(log2FoldChange.x), y=(log2FoldChange.y))) + theme_classic() + geom_hline(yintercept=0, lty=3) + geom_vline(xintercept=0, lty=3) + xlab("Vero Nutlin-3a vs. DMSO\nLog2 Fold Change, ATAC-seq") + ylab("Vero Delta vs. EGFP\nLog2 Fold Change, ATAC-seq")

ggplot(subset(merge(atac_results_vero_nut, vero_alpha_results, by=0), padj.x < 00.05 & padj.y < 00.05)) + geom_point(aes(x=(log2FoldChange.x), y=(log2FoldChange.y)), alpha=0.2, pch=1) + xlim(c(-3.5,3.5)) + ylim(c(-3.5,3.5)) + geom_smooth(method="lm", formula=y~x, aes(x=(log2FoldChange.x), y=(log2FoldChange.y))) + theme_classic() + geom_hline(yintercept=0, lty=3) + geom_vline(xintercept=0, lty=3) + xlab("Vero Nutlin-3a vs. DMSO\nLog2 Fold Change, ATAC-seq") + ylab("Vero Alpha vs. EGFP\nLog2 Fold Change, ATAC-seq")

ggplot(subset(merge(atac_results_vero_nut, vero_spike_results, by=0), padj.x < 00.05 & padj.y < 00.05)) + geom_point(aes(x=(log2FoldChange.x), y=(log2FoldChange.y)), alpha=0.2, pch=1) + xlim(c(-3.5,3.5)) + ylim(c(-3.5,3.5)) + geom_smooth(method="lm", formula=y~x, aes(x=(log2FoldChange.x), y=(log2FoldChange.y))) + theme_classic() + geom_hline(yintercept=0, lty=3) + geom_vline(xintercept=0, lty=3) + xlab("Vero Nutlin-3a vs. DMSO\nLog2 Fold Change, ATAC-seq") + ylab("Vero Spike vs. EGFP\nLog2 Fold Change, ATAC-seq")
```



